#!/usr/bin/env python3

#
# Test the EPrint DB connection as defined in settings.ini
#

import os
import sys

from decouple import config

from acacia.eprints import EPrintsDB

_db = config('EPRINT_DATABASE', None)

if __name__ == '__main__':
    if _db == None:
        print(f'EPRINT_DATABASE not defined in settings.ini')
        sys.exit(1)
    try:
        eprints_db = EPrintsDB(_db)
    except Exception as err:
        print(f'Failed to initialize eprints_db, {err}')
        sys.exit(1)
    doi = '10.1364/OL.20.002222'
    eprint_id = eprints_db.get_eprint_id_by_doi(doi)
    print(f'DOI: {doi} -> eprint_id: {eprint_id}')
