#!/usr/bin/env python3

#
# Test the EPrint DB reports via SSH as defined in settings.ini
#

import os
import sys

from decouple import config

from acacia.eprints import EPrintsSSH

connect = config('EPRINT_SSH', None)
repo_id = config('EPRINT_REPO_ID', None)

if __name__ == '__main__':
    if connect == None:
        print(f'EPRINT_SSH not defined in settings.ini')
        sys.exit(1)
    if repo_id == None:
        print(f'EPRINT_REPO_ID not defined in settings.ini')
        sys.exit(1)
    eprints_ssh = EPrintsSSH(connect, repo_id)
    doi = '10.1364/OL.20.002222'
    eprint_id = eprints_ssh.get_eprint_id_by_doi(doi)
    print(f'DOI: {doi} -> eprint_id: {eprint_id}')
